language: python

branches:
  only:
    - travis
    - dockerized

python:
  - "2.7"

services: mongodb

# command to install dependencies
install: "pip install -r requirements.txt"

before_script:
    # - git config --global user.name [myname]
    # - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
    # - echo 'deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen' | sudo tee /etc/apt/sources.list.d/mongodb.list
    # - sudo apt-get update
    # - sudo apt-get install -y mongodb-org=2.4.6 mongodb-org-server=2.4.6 mongodb-org-shell=2.4.6 mongodb-org-mongos=2.4.6 mongodb-org-tools=2.4.6
    - sleep 15 #mongo may not be responded directly. See http://docs.travis-ci.com/user/database-setup/#MongoDB
    - mongo --version

notifications:
  email: "yannick.congo@gmail.com"

# command to run tests
script: 
  - nosetests -w tests/ --with-doctest -v
